version: '3.8'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "${DOCKER_PORT_NGINX:-8080}:80"
    volumes:
      - ./:/var/www/app:ro
    networks:
      - app_network
    depends_on:
      - php

  php:
    restart: always
    container_name: loanphp
    command: bash -c "chmod +x /var/www/app/docker/php/entrypoint.sh && /var/www/app/docker/php/entrypoint.sh"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: app_php
    volumes:
      - ./:/var/www/app:rw,delegated
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    shm_size: 1g
    build:
      context: ./docker/postgres
    restart: unless-stopped
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DB_NAME},${TEST_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_PORT_POSTGRES:-5433}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
